apiVersion: v1
kind: Namespace
metadata:
  name: opa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--config-file=/config/config.yaml"
          ports:
            - containerPort: 8181
              name: https
          volumeMounts:
            # OPA config
            - name: opa-config
              mountPath: /config
              readOnly: true

            # TLS secret mount
            - name: opa-tls
              mountPath: /certs
              readOnly: true

      volumes:
        # ConfigMap volume
        - name: opa-config
          configMap:
            name: opa-config

        # TLS Secret volume
        - name: opa-tls
          secret:
            secretName: opa-tls